---
- name: Install PM2 and Configure Nginx Reverse Proxy
  hosts: web
  remote_user: ubuntu

  tasks:
    - name: Install necessary packages
      become: yes
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Install nodejs and npm
      become: yes
      apt:
        pkg:
          - nodejs
          - npm
        state: present

    - name: Install PM2 globally
      become: true
      ansible.builtin.npm:
        name: pm2
        global: yes


    - name: Install dependencies
      shell: |
        cd /home/ubuntu/app
        npm install

    - name: Check if PM2 is running
      become: true
      ansible.builtin.shell: "pm2 status app"
      register: pm2_status
      ignore_errors: yes

    - name: Start Express.js app with PM2 if not already running
      become: true
      ansible.builtin.command: "pm2 start /home/ubuntu/app/index.js --name app"
      when: pm2_status.rc != 0

    - name: Copy default.conf to Nginx conf.d directory
      become: true
      ansible.builtin.copy:
        src: /home/ubuntu/app/ansible/default.conf
        dest: /etc/nginx/conf.d/default.conf
      notify: Restart Nginx  

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
